In [1]:
# Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
# a) Addition of 2 in all the element
import numpy as np
a=np.array([0,1,2,3,4])
a=a+2
print(a)

[2 3 4 5 6]


In [2]:
 # b) Multiply 3 with all the elements
b=np.array([1,2,3,4,5])
b=b*3
print(b)

[ 3  6  9 12 15]


In [3]:
# c) Divide every element by 2
b=np.array([10,8,6,4,2])
b=b/2
print(b)

[5. 4. 3. 2. 1.]


In [4]:
# Q.2 Questions on Basic NumPy Array:
# a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
arr=np.array([1,2,3,4,5])
arr=np.flip(arr)
print(arr)

[5 4 3 2 1]


In [5]:
# b) Find the most frequent value and their indice(s) in the following arrays:
# i. x = np.array([1,2,3,4,5,1,2,1,1,1])
from statistics import mode
x=np.array([1,2,3,4,5,1,2,1,1,1])
a=(mode(x))
print("most frequent element",a)
print("mode is occuring at")
for i in range(0,len(x)-1):
    if x[i]==a:
     print(i+1)

most frequent element 1
mode is occuring at
1
6
8
9


In [6]:
# ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
from statistics import mode
x=np.array([1,1,1,2,3,4,2,4,3,3])
a=(mode(x))
print("most frequent element",a)
print("mode is occuring at")
for i in range(0,len(x)-1):
    if x[i]==a:
     print(i+1)




most frequent element 1
mode is occuring at
1
2
3


In [ ]:
# Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:
# a) Access 1st row, 2nd column
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
arr[0,1]

[[10 20 30]
 [40 50 60]
 [70 80 90]]


20

In [ ]:
# b) Access 3rd row, 1st column
arr[2,0]

70

In [7]:
'''Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?'''

yashika=np.linspace(10,100,25)
print(yashika)
print("dimensions",yashika.ndim)
print("shape",yashika.shape)
print("total elements",yashika.size)
print("data type",yashika.dtype)
print("bytes",yashika.nbytes)


transpose=yashika.reshape(25,1)
print("transpose ",transpose)


print("using t attribute \n",yashika.T)


[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
dimensions 1
shape (25,)
total elements 25
data type float64
bytes 200
transpose  [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
using t attribute 
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [8]:
'''Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.'''


ucs420_yashika=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,30]])
print(ucs420_yashika)
print("mean",np.mean(ucs420_yashika))
print("median",np.median(ucs420_yashika))
print("maximum",np.max(ucs420_yashika))
print("minimum",np.min(ucs420_yashika))
print("unique elements",np.unique(ucs420_yashika))


reshaped_ucs420_yashika=ucs420_yashika.reshape(4,3)
print("transpose",reshaped_ucs420_yashika)

resized_ucs420_yashika=np.resize(ucs420_yashika,(2,3))
print("resized\n",resized_ucs420_yashika)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 30]]
mean 42.916666666666664
median 35.0
maximum 90
minimum 10
unique elements [10 15 20 30 40 50 60 70 80 90]
transpose [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 30]]
resized
 [[10 20 30]
 [40 50 60]]
